# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_DIR     = /Applications/Arduino.app/Contents/Java
ARDMK_DIR       = /usr/local/opt/arduino-mk
AVR_TOOLS_DIR   = /Applications/Arduino.app/Contents/Java/hardware/tools/avr/
MONITOR_PORT    = /dev/cu.wchusbserialfa120
BOARD_TAG    	= uno

include /usr/local/opt/arduino-mk/Arduino.mk
